In [1]:
import pandas as pd


read_csv = pd.read_csv(r"C:\Users\zalak\Downloads\customers-1000.csv")
read_csv.head()

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1,dE014d010c7ab0c,Andrew,Goodman,Stewart-Flynn,Rowlandberg,Macao,846-790-4623x4715,(422)787-2331x71127,marieyates@gomez-spencer.info,2021-07-26,http://www.shea.biz/
1,2,2B54172c8b65eC3,Alvin,Lane,"Terry, Proctor and Lawrence",Bethside,Papua New Guinea,124-597-8652x05682,321.441.0588x6218,alexandra86@mccoy.com,2021-06-24,http://www.pena-cole.com/
2,3,d794Dd48988d2ac,Jenna,Harding,Bailey Group,Moniquemouth,China,(335)987-3085x3780,001-680-204-8312,justincurtis@pierce.org,2020-04-05,http://www.booth-reese.biz/
3,4,3b3Aa4aCc68f3Be,Fernando,Ford,Moss-Maxwell,Leeborough,Macao,(047)752-3122,048.779.5035x9122,adeleon@hubbard.org,2020-11-29,http://www.hebert.com/
4,5,D60df62ad2ae41E,Kara,Woods,Mccarthy-Kelley,Port Jacksonland,Nepal,+1-360-693-4419x19272,163-627-2565,jesus90@roberson.info,2022-04-22,http://merritt.com/

In [4]:
# To Display Maximum column & Rows
pd.set_option("display.max.columns" , 6)
pd.set_option("display.max.rows" , 60)

In [61]:
read_csv.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   First Name  1000 non-null   object
 1   Email       1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

In [ ]:
read_csv.head(5)

In [ ]:
read_csv.tail(5)

In [ ]:
# I want specific columns from my dataset...
# Possile by Multiple Ways

subset1 = read_csv[["First Name", "Email"]]
subset1



# We can use below as well
# df = pd.read_csv("your_file.csv", usecols=['First Name', 'Website'])

    First Name                          Email
0       Andrew  marieyates@gomez-spencer.info
1        Alvin          alexandra86@mccoy.com
2        Jenna        justincurtis@pierce.org
3     Fernando            adeleon@hubbard.org
4         Kara          jesus90@roberson.info
..         ...                            ...
995      Diana     cassidymercado@bonilla.com
996      Jerry        gavin13@logan-downs.com
997     Tracie         lowehailey@oconnor.org
998       Paul   hodgeseddie@hardin-wells.com
999    Dominic         owarner@velasquez.info

[1000 rows x 2 columns]

In [ ]:
# By loc() function - is a label-based data selection method in pandas. It allows you to slice and dice your DataFrame using row labels, column labels

# df.loc[row_indexer, column_indexer]
# row_indexer = Specifies which rows to select — can be a single label, list/slice of labels, boolean array, or even a callable.
# column_indexer = Specifies which columns to select — again, can be labels, lists, slices, boolean arrays, or callables.

subset2 = read_csv.loc[:, ["First Name", "Email"]]
subset2

    First Name                          Email
0       Andrew  marieyates@gomez-spencer.info
1        Alvin          alexandra86@mccoy.com
2        Jenna        justincurtis@pierce.org
3     Fernando            adeleon@hubbard.org
4         Kara          jesus90@roberson.info
..         ...                            ...
995      Diana     cassidymercado@bonilla.com
996      Jerry        gavin13@logan-downs.com
997     Tracie         lowehailey@oconnor.org
998       Paul   hodgeseddie@hardin-wells.com
999    Dominic         owarner@velasquez.info

[1000 rows x 2 columns]

In [77]:
# We can check for specific Row as well
subset3 = read_csv.loc[0:3]
subset3

,Index,Customer Id,First Name,...,Email,Subscription Date,Website
0,1,dE014d010c7ab0c,Andrew,...,marieyates@gomez-spencer.info,2021-07-26,http://www.shea.biz/
1,2,2B54172c8b65eC3,Alvin,...,alexandra86@mccoy.com,2021-06-24,http://www.pena-cole.com/
2,3,d794Dd48988d2ac,Jenna,...,justincurtis@pierce.org,2020-04-05,http://www.booth-reese.biz/
3,4,3b3Aa4aCc68f3Be,Fernando,...,adeleon@hubbard.org,2020-11-29,http://www.hebert.com/