In [ ]:
import pandas as pd
r_excel = pd.read_excel(r"C:\Users\zalak\Downloads\student (1).xlsx")
r_excel

In [8]:
r_excel.head(2)

   id      name  class  mark  gender
0   1  John Deo   Four    75  female
1   2  Max Ruin  Three    85    male

In [9]:
r_excel.tail(3)

    id        name  class  mark  gender
32  33   Kenn Rein    Six    96  female
33  34    Gain Toe  Seven    69    male
34  35  Rows Noump    Six    88  female

In [17]:
r_excel.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35 entries, 0 to 34
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      35 non-null     int64
 1   name    35 non-null     object
 2   class   35 non-null     object
 3   mark    35 non-null     int64
 4   gender  35 non-null     object
dtypes: int64(2), object(3)
memory usage: 1.5+ KB

In [11]:
r_excel.describe()

              id       mark
count  35.000000  35.000000
mean   18.000000  74.657143
std    10.246951  16.401117
min     1.000000  18.000000
25%     9.500000  62.500000
50%    18.000000  79.000000
75%    26.500000  88.000000
max    35.000000  96.000000

In [18]:
r_excel.shape

(35, 5)

In [20]:
r_excel.columns

Index(['id', 'name', 'class', 'mark', 'gender'], dtype='object')

In [21]:
r_excel.index

RangeIndex(start=0, stop=35, step=1)

# Change Specific Column name or multiple column names

In [ ]:
read_csv = pd.read_csv(r"C:\Users\zalak\Downloads\customers-1000.csv")
read_csv.head(2)

In [8]:
# Single Column Rename

modified_df = read_csv.rename( columns = { "Customer Id" : "c_id" } )
modified_df.head(2)

,Index,c_id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1,dE014d010c7ab0c,Andrew,Goodman,Stewart-Flynn,Rowlandberg,Macao,846-790-4623x4715,(422)787-2331x71127,marieyates@gomez-spencer.info,2021-07-26,http://www.shea.biz/
1,2,2B54172c8b65eC3,Alvin,Lane,"Terry, Proctor and Lawrence",Bethside,Papua New Guinea,124-597-8652x05682,321.441.0588x6218,alexandra86@mccoy.com,2021-06-24,http://www.pena-cole.com/

In [9]:
# Multiple Column Rename

read_csv.rename( columns = { "First Name":"f_name" , "Last Name":"l_name" , "Country":"Nation" } , inplace = True )
read_csv.columns

Index(['Index', 'Customer Id', 'f_name', 'l_name', 'Company', 'City', 'Nation',
       'Phone 1', 'Phone 2', 'Email', 'Subscription Date', 'Website'],
      dtype='object')

In [10]:
# Modify all column names
read_csv.columns = ["index","cus_id" , "firstName" , "lastName" , "Organization" , "city" ,"Country" , "Phone" , "Telephone" , "Mail" , "Starting_Date" , "site"]
read_csv.head(2)

,index,cus_id,firstName,lastName,Organization,city,Country,Phone,Telephone,Mail,Starting_Date,site
0,1,dE014d010c7ab0c,Andrew,Goodman,Stewart-Flynn,Rowlandberg,Macao,846-790-4623x4715,(422)787-2331x71127,marieyates@gomez-spencer.info,2021-07-26,http://www.shea.biz/
1,2,2B54172c8b65eC3,Alvin,Lane,"Terry, Proctor and Lawrence",Bethside,Papua New Guinea,124-597-8652x05682,321.441.0588x6218,alexandra86@mccoy.com,2021-06-24,http://www.pena-cole.com/

# Drop Specific or Multiple Columns

In [ ]:
# Drop Single Column
dropSingleCol_df = read_csv.drop(columns = ["index"])
dropSingleCol_df.head(2)

,cus_id,firstName,lastName,Organization,city,Country,Phone,Telephone,Mail,Starting_Date,site
0,dE014d010c7ab0c,Andrew,Goodman,Stewart-Flynn,Rowlandberg,Macao,846-790-4623x4715,(422)787-2331x71127,marieyates@gomez-spencer.info,2021-07-26,http://www.shea.biz/
1,2B54172c8b65eC3,Alvin,Lane,"Terry, Proctor and Lawrence",Bethside,Papua New Guinea,124-597-8652x05682,321.441.0588x6218,alexandra86@mccoy.com,2021-06-24,http://www.pena-cole.com/

In [20]:
# Drop Multiple Column
dropMultiCol_df = read_csv.drop( columns = ["site" , "Organization" , "Starting_Date"] )
dropMultiCol_df.head(2)

,index,cus_id,firstName,lastName,city,Country,Phone,Telephone,Mail
0,1,dE014d010c7ab0c,Andrew,Goodman,Rowlandberg,Macao,846-790-4623x4715,(422)787-2331x71127,marieyates@gomez-spencer.info
1,2,2B54172c8b65eC3,Alvin,Lane,Bethside,Papua New Guinea,124-597-8652x05682,321.441.0588x6218,alexandra86@mccoy.com