groupby() → makes groups.
agg() → summarizes each group.

What is Aggregation ?
----------------------
aggregation = applying a function (like mean, sum, min, max, count, etc.) to reduce 
values in each group into a single summary value.

Example: If you have salaries [4000, 4200] in HR, their mean = 4100.
That’s aggregation: many values → one summary value per group.

Syntax Breakdown
----------------
df.groupby("GroupColumn")["TargetColumn"].agg(["func1", "func2", ...])

GroupColumn → column(s) to group by (e.g. "Department")
TargetColumn → column(s) you want to aggregate (e.g. "Salary")
agg([...]) → list of aggregation functions to apply

In [2]:
import pandas as pd

In [6]:
E_data = {
    "Department": ["HR", "HR", "IT", "IT", "Finance", "Finance","Marketing","Sales","Mfg"],
    "Total Employee": [5, 25, 65, 80, 52, 48,34,23,59],
    "Salary": [4000, 4200, 5000, 5500, 6000, 5800,24454,6543,4244],
    "Bonus": [200, 250, 300, 400, 500, 450,766,7889,4356]
}

EmpDf = pd.DataFrame(E_data)
EmpDf

  Department  Total Employee  Salary  Bonus
0         HR               5    4000    200
1         HR              25    4200    250
2         IT              65    5000    300
3         IT              80    5500    400
4    Finance              52    6000    500
5    Finance              48    5800    450
6  Marketing              34   24454    766
7      Sales              23    6543   7889
8        Mfg              59    4244   4356

In [19]:
# Give me Average salary of each department
EmpDf.groupby("Department")["Salary"].agg("mean")

Department
Finance       5900.0
HR            4100.0
IT            5250.0
Marketing    24454.0
Mfg           4244.0
Sales         6543.0
Name: Salary, dtype: float64

In [20]:
# Give avg. salary & avg. bonus of each department

EmpDf.groupby("Department").agg({
    "Salary":"mean",
    "Bonus":"mean"
})
# NOTE : We can get what specific we want from specific column...Which we type in agg() function

             Salary   Bonus
Department
Finance      5900.0   475.0
HR           4100.0   225.0
IT           5250.0   350.0
Marketing   24454.0   766.0
Mfg          4244.0  4356.0
Sales        6543.0  7889.0

In [21]:
# How many employees in each department
EmpDf.groupby("Department")["Total Employee"].agg("sum")

Department
Finance      100
HR            30
IT           145
Marketing     34
Mfg           59
Sales         23
Name: Total Employee, dtype: int64

In [22]:
# In each department find Max. & Min. Salary and Bonus
EmpDf.groupby("Department").agg({
    "Salary":["max","min"],
    "Bonus":["max","min"]
})

           Salary        Bonus
              max    min   max   min
Department
Finance      6000   5800   500   450
HR           4200   4000   250   200
IT           5500   5000   400   300
Marketing   24454  24454   766   766
Mfg          4244   4244  4356  4356
Sales        6543   6543  7889  7889