In [5]:
import numpy as np
import pandas as pd
from pandas import DataFrame

rank = {
    "name":   ["Liam", "Olivia", "Noah", "Emma", "Oliver", "Ava", "Elijah", "Sophia"],
    "age":    [25,  29,     22,    28,    33,      27,    24,      31],
    "gender": ["Male","Female","Male","Female","Male","Female","Male","Female"],
    "rank": [1,2,3,4,5,6,7,8]
}

rank_df = DataFrame(rank)
rank_df

     name  age  gender  rank
0    Liam   25    Male     1
1  Olivia   29  Female     2
2    Noah   22    Male     3
3    Emma   28  Female     4
4  Oliver   33    Male     5
5     Ava   27  Female     6
6  Elijah   24    Male     7
7  Sophia   31  Female     8

In [10]:
rank_df.iloc[1:3, 0] = np.nan
rank_df.iloc[4:6, 1] = np.nan
rank_df.iloc[0:4, 2] = np.nan
rank_df.iloc[3,:] = np.nan

rank_df

     name   age  gender  rank
0    Liam  25.0     NaN   1.0
1     NaN  29.0     NaN   2.0
2     NaN  22.0     NaN   3.0
3     NaN   NaN     NaN   NaN
4  Oliver   NaN    Male   5.0
5     Ava   NaN  Female   6.0
6  Elijah  24.0    Male   7.0
7  Sophia  31.0  Female   8.0

In [7]:
# Check for null values
rank_df.isnull()

# There is another method for find null values
# rank_df.notnul()

    name    age  gender   rank
0  False  False    True  False
1   True  False    True  False
2   True  False    True  False
3   True   True    True   True
4  False   True   False  False
5  False   True   False  False
6  False  False   False  False
7  False  False   False  False

In [8]:
# fetch out rows based on Null value of specific column

nullAge_df = pd.isnull(rank_df["age"])  # It's called Mask object
rank_df[nullAge_df]

     name  age  gender  rank
3     NaN  NaN     NaN   NaN
4  Oliver  NaN    Male   5.0
5     Ava  NaN  Female   6.0

# Fill missing values

In [9]:
rank_df.fillna(method="pad")
# Fill previous cell value in NaN cell

C:\Users\zalak\AppData\Local\Temp\ipykernel_19844\3210109053.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  rank_df.fillna(method="pad")

     name   age  gender  rank
0    Liam  25.0     NaN   1.0
1    Liam  29.0     NaN   2.0
2    Liam  22.0     NaN   3.0
3    Liam  22.0     NaN   3.0
4  Oliver  22.0    Male   5.0
5     Ava  22.0  Female   6.0
6  Elijah  24.0    Male   7.0
7  Sophia  31.0  Female   8.0

In [11]:
rank_df.fillna(method="bfill")
# Fill below cell value in NaN cell

C:\Users\zalak\AppData\Local\Temp\ipykernel_19844\905922078.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  rank_df.fillna(method="bfill")

     name   age  gender  rank
0    Liam  25.0    Male   1.0
1  Oliver  29.0    Male   2.0
2  Oliver  22.0    Male   3.0
3  Oliver  24.0    Male   5.0
4  Oliver  24.0    Male   5.0
5     Ava  24.0  Female   6.0
6  Elijah  24.0    Male   7.0
7  Sophia  31.0  Female   8.0

In [12]:
rank_df.interpolate(method="linear")

C:\Users\zalak\AppData\Local\Temp\ipykernel_19844\139066799.py:1: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  rank_df.interpolate(method="linear")

     name   age  gender  rank
0    Liam  25.0     NaN   1.0
1     NaN  29.0     NaN   2.0
2     NaN  22.0     NaN   3.0
3     NaN  22.5     NaN   4.0
4  Oliver  23.0    Male   5.0
5     Ava  23.5  Female   6.0
6  Elijah  24.0    Male   7.0
7  Sophia  31.0  Female   8.0

In [13]:
# dropna() = drop all the cell which has NaN value or It can be said give data frame with No NaN values
rank_df.dropna()

     name   age  gender  rank
6  Elijah  24.0    Male   7.0
7  Sophia  31.0  Female   8.0