In [10]:
import numpy as np
import pandas as pd
from pandas import DataFrame

data = {
    "name": ["Alice", "Bob", "Alice", "Charlie", "Bob", "Charlie", "Alice"],
    "age":  [25, 30, 25, 40, 30, 25, 30],
    "city": ["NY", "LA", "NY", "SF", "LA", "LA", "LA"]
}

obj_df = DataFrame(data)
obj_df

      name  age city
0    Alice   25   NY
1      Bob   30   LA
2    Alice   25   NY
3  Charlie   40   SF
4      Bob   30   LA
5  Charlie   25   LA
6    Alice   30   LA

In [11]:
# To Check for each Row is there any duplicate value or not
"""
It check all 3 column 
like [Alice	25	NY] is at Row 0 = False & again it repet at Row 2 , so it's True

if duplicate values found then True else False
"""
obj_df.duplicated()

0    False
1    False
2     True
3    False
4     True
5    False
6    False
dtype: bool

In [12]:
# To Drop duplicate values

obj_df.drop_duplicates()

      name  age city
0    Alice   25   NY
1      Bob   30   LA
3  Charlie   40   SF
5  Charlie   25   LA
6    Alice   30   LA

In [14]:
# To Drop duplicate values on a specific column
obj_df.drop_duplicates(subset="city")

      name  age city
0    Alice   25   NY
1      Bob   30   LA
3  Charlie   40   SF