# Very Important

DIFFERENT JOIN TYPES
![alt text](<Screenshot 2025-09-27 132458-1.png>)

In [37]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [38]:
dfObj1 = DataFrame(np.arange(36).reshape(6,6))
dfObj1

    0   1   2   3   4   5
0   0   1   2   3   4   5
1   6   7   8   9  10  11
2  12  13  14  15  16  17
3  18  19  20  21  22  23
4  24  25  26  27  28  29
5  30  31  32  33  34  35

In [39]:
obj2_df = DataFrame(np.arange(15).reshape(5,3))
obj2_df

    0   1   2
0   0   1   2
1   3   4   5
2   6   7   8
3   9  10  11
4  12  13  14

# Concatination of DataFrame

In [54]:
sum_obj1_obj2 = pd.concat(
    [dfObj1, obj2_df]
)
sum_obj1_obj2

# Default It concatinate by Row

    0   1   2     3     4     5
0   0   1   2   3.0   4.0   5.0
1   6   7   8   9.0  10.0  11.0
2  12  13  14  15.0  16.0  17.0
3  18  19  20  21.0  22.0  23.0
4  24  25  26  27.0  28.0  29.0
5  30  31  32  33.0  34.0  35.0
0   0   1   2   NaN   NaN   NaN
1   3   4   5   NaN   NaN   NaN
2   6   7   8   NaN   NaN   NaN
3   9  10  11   NaN   NaN   NaN
4  12  13  14   NaN   NaN   NaN

In [64]:
# Now , in above data frame index is not proper , to fix it

sum_obj1_obj2 = pd.concat(
    
    [dfObj1, obj2_df],
    ignore_index = True
)
sum_obj1_obj2

     0   1   2     3     4     5
0    0   1   2   3.0   4.0   5.0
1    6   7   8   9.0  10.0  11.0
2   12  13  14  15.0  16.0  17.0
3   18  19  20  21.0  22.0  23.0
4   24  25  26  27.0  28.0  29.0
5   30  31  32  33.0  34.0  35.0
6    0   1   2   NaN   NaN   NaN
7    3   4   5   NaN   NaN   NaN
8    6   7   8   NaN   NaN   NaN
9    9  10  11   NaN   NaN   NaN
10  12  13  14   NaN   NaN   NaN

In [ ]:
sum_obj1_obj2_column = pd.concat(

    [dfObj1, obj2_df], 
    axis = 1
)
sum_obj1_obj2_column

# Now, It concatinate by Column , default by Row

    0   1   2   3   4   5     0     1     2
0   0   1   2   3   4   5   0.0   1.0   2.0
1   6   7   8   9  10  11   3.0   4.0   5.0
2  12  13  14  15  16  17   6.0   7.0   8.0
3  18  19  20  21  22  23   9.0  10.0  11.0
4  24  25  26  27  28  29  12.0  13.0  14.0
5  30  31  32  33  34  35   NaN   NaN   NaN

# Droping Data

In [56]:
dfObj1

    0   1   2   3   4   5
0   0   1   2   3   4   5
1   6   7   8   9  10  11
2  12  13  14  15  16  17
3  18  19  20  21  22  23
4  24  25  26  27  28  29
5  30  31  32  33  34  35

In [57]:
dfObj1.drop([0,3,5])

# Drop specific Row like row num. 0,3,5 are drop

    0   1   2   3   4   5
1   6   7   8   9  10  11
2  12  13  14  15  16  17
4  24  25  26  27  28  29

In [58]:
dfObj1.drop(dfObj1.index[0:3])

# Drop Rows in specific Range

    0   1   2   3   4   5
3  18  19  20  21  22  23
4  24  25  26  27  28  29
5  30  31  32  33  34  35

In [59]:
dfObj1.drop([4,5], axis=1)

# Drop specific Column like Col. num. 4 and 5

    0   1   2   3
0   0   1   2   3
1   6   7   8   9
2  12  13  14  15
3  18  19  20  21
4  24  25  26  27
5  30  31  32  33

In [60]:
dfObj1.drop(dfObj1.index[1:3], axis=1)

# Drop Columns specific range

    0   3   4   5
0   0   3   4   5
1   6   9  10  11
2  12  15  16  17
3  18  21  22  23
4  24  27  28  29
5  30  33  34  35

# Add Data Using Join ()

In [61]:
dfObj1

    0   1   2   3   4   5
0   0   1   2   3   4   5
1   6   7   8   9  10  11
2  12  13  14  15  16  17
3  18  19  20  21  22  23
4  24  25  26  27  28  29
5  30  31  32  33  34  35

In [62]:
Series_obj = Series(np.arange(9))
Series_obj.name = "New Column"
Series_obj

0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
Name: New Column, dtype: int64

In [63]:
joined_df = DataFrame.join(dfObj1, Series_obj)
joined_df

    0   1   2   3   4   5  New Column
0   0   1   2   3   4   5           0
1   6   7   8   9  10  11           1
2  12  13  14  15  16  17           2
3  18  19  20  21  22  23           3
4  24  25  26  27  28  29           4
5  30  31  32  33  34  35           5